#!/bin/bash

function usage {
	echo "To install:"
	echo ""
	echo "./install <distro>"
	echo "	*For RHEL/CentOS: `rhel`"
	echo "	*For Debian/Ubuntu: `deb`"
	echo "	*For Suse: `suse`"
}

if [ -z "$1" ]
 then
	usage
	exit 2
fi

#Make sure you're root.
id | grep "uid=0(root)" > /dev/null
if [ $? -ne 0 ]
 then
	echo "Must be root to run this install script."
	exit 1
fi

case $1 in
  rhel)
	yum -y install python-setuptools python-paramiko python-prettytable ipmitool
	if [ $? -ne 0 ]
	 then
		echo ""
		echo ""
		echo "ERROR: You probably are missing repos, or if you're running RHEL, you have not yet been activated."
		echo ""
		echo ""
	fi

	python setup.py install
	;;
  deb)
	echo "Support for debian is not tested."
	apt-get -y install python2-pip
	if [ $? -ne 0 ]
	 then
		echo ""
		echo ""
		echo "ERROR: You probably are missing repos."
		echo ""
		echo ""
	fi
	python setup.py install
	;;
  suse)
  	echo "Support for suse is not yet tested."
	zypper -y install python-setuptools python-paramiko python-prettytable
	if [ $? -ne 0 ]
	 then
		echo ""
		echo ""
		echo "You probably are missing repos, or you have not yet activated the repos."
		echo ""
		echo ""
	fi

	# ...And we should probably be making sure that yum isn't failing.
	python setup.py install
	;;
  *)
	echo "Unknown install type: ${1}, exiting."
	exit 10
	;;
esac
